# Dockerfile para desarrollo con hot reload
FROM node:lts-alpine

WORKDIR /app

# Instalar pnpm globalmente
RUN npm install -g pnpm

# Configuraciones necesarias de pnpm
RUN pnpm config set fetch-retry-mintimeout=100
RUN pnpm config set fetch-retry-maxtimeout=100
RUN pnpm config set fetch-retries=1000000

# Copiar todo el proyecto
COPY . .

# Instalar dependencias
RUN pnpm install --frozen-lockfile

# Otorgar permisos de ejecucion al script inicial de la app
RUN chmod +x ./docker-entrypoint.dev.sh

# Exponer el puerto de la aplicación
EXPOSE 3000

# Comando para ejecutar el script de entrada
ENTRYPOINT ["./docker-entrypoint.dev.sh"] 